# Generated by Django 5.0.3 on 2024-03-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                ],
                default="New",
                max_length=50,
            ),
        ),
    ]
