# Generated by Django 5.0.3 on 2024-03-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistancerequest",
            name="incurred_problem",
            field=models.CharField(
                choices=[
                    ("Flat Tire", "Flat Tire"),
                    ("Battery Issues", "Battery Issues"),
                    ("Engine Trouble", "Engine Trouble"),
                    ("Fuel Problem", "Fuel Problem"),
                    ("Other", "Other"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
